import type { Metadata } from "next";
import "./globals.css";
import ApolloWrapper from "@/components/ApolloWrapper";


export const metadata: Metadata = {
  title: "Pre-Inspected Used Cars",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ApolloWrapper>
            {children}
        </ApolloWrapper>
       
      </body>
    </html>
  );
}
