import type { Metadata } from "next";
import "./globals.css";
import ApolloWrapper from "@/components/ApolloWrapper";
import Head from "next/head";
import Script from "next/script";

export const metadata: Metadata = {
  title: "Pre-Inspected Used Cars",
  description: "Generated by create next app",
};


export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

 console.log('Layout rendering on:', typeof window === 'undefined' ? 'server' : 'client');


  return (
    <html lang="en" className="overflow-x-hidden bg-white">
     
        <Script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/7.0.1/css/all.min.css" />
      
      <body className="bg-lightGray">
        <ApolloWrapper>
            {children}
        </ApolloWrapper>
         {/* Debug script */}
        <script dangerouslySetInnerHTML={{
          __html: `
            console.log('Client-side mount');
            window.addEventListener('error', (e) => {
              console.error('Caught error:', e.error);
            });
          `
        }} />
      </body>
    </html>
  );
}
