let cars = [
    { id: '1', model: 'Mazda CX-5', location: 'Makuyu'},
    { id: '2', model: 'Mazda CX-4', location: 'Makuya'},
    { id: '3', model: 'Mazda CX-04', location: 'Makuyaa'},
    { id: '4', model: 'Mazda CX-3', location: 'Makuyi'},
    { id: '5', model: 'Mazda CX-2', location: 'Makulu'},
    { id: '6', model: 'Mazda CX-10', location: 'Makuyus'}
];
let carspecifications = [
    { id: '1', price: "200,00", mileage: "300", engine_size: "300cc",
        engine_power: "422 Hp", fuel: "20 km per Liter", year: "2009", reg_no: "KDB 892U",
        color: "yellow" },
    { id: '2', price: "300,00", mileage: "400", engine_size: "500cc",
        engine_power: "412 Hp", fuel: "5 km per Liter", year: "2018", reg_no: "KCB 892U",
        color: "black" },
    { id: '3', price: "320,00", mileage: "190", engine_size: "200cc",
        engine_power: "223 Hp", fuel: "10 km per Liter", year: "2005", reg_no: "KDN 789S",
        color: "white" },
    { id: '4', price: "590,00", mileage: "50", engine_size: "390cc",
        engine_power: "181 Hp", fuel: "20 km per Liter", year: "2009", reg_no: "KCS 157H",
        color: "blue" },
    { id: '5', price: "181,00", mileage: "600", engine_size: "400cc",
        engine_power: "500 Hp", fuel: "20 km per Liter", year: "2012", reg_no: "KBJ 529J",
        color: "silver" },
    { id: '6', price: "195,00", mileage: "300", engine_size: "300cc",
        engine_power: "422 Hp", fuel: "20 km per Liter", year: "2009", reg_no: "KAP 621A",
        color: "maroon" }
];
let carshistory = [
    { id: "1",
        insurance_write_off: "yes",
        not_scrapped: "yes",
        not_stolen: "no",
        original_plate: "yes",
        latest_owner: "yes",
        inspection_report: "yes",
    },
    {
        id: "2",
        insurance_write_off: "yes",
        not_scrapped: "yes",
        not_stolen: "no",
        original_plate: "yes",
        latest_owner: "yes",
        inspection_report: "yes",
    },
    {
        id: "3",
        insurance_write_off: "yes",
        not_scrapped: "yes",
        not_stolen: "no",
        original_plate: "yes",
        latest_owner: "yes",
        inspection_report: "yes",
    },
    {
        id: "4",
        insurance_write_off: "yes",
        not_scrapped: "yes",
        not_stolen: "no",
        original_plate: "yes",
        latest_owner: "yes",
        inspection_report: "yes",
    },
    {
        id: "5",
        insurance_write_off: "yes",
        not_scrapped: "yes",
        not_stolen: "no",
        original_plate: "yes",
        latest_owner: "yes",
        inspection_report: "yes",
    },
    {
        id: "6",
        insurance_write_off: "yes",
        not_scrapped: "yes",
        not_stolen: "no",
        original_plate: "yes",
        latest_owner: "yes",
        inspection_report: "yes",
    }
];
export default { cars, carspecifications, carshistory };
